---
- name: Get MySQL version
  block:
    - name: Run mysql --version
      ansible.builtin.command: '{{ mysql_daemon }} --version'
      register: mysql_cli_version
      changed_when: false
      check_mode: false

    - name: Extract MySQL version
      ansible.builtin.set_fact:
        mysql_cli_version: >-
          {{ mysql_cli_version.stdout | regex_search('\d+\.\d+\.\d+(-[a-zA-Z]+)?') }}

- name: Copy my.cnf global MySQL configuration.
  ansible.builtin.template:
    src: my.cnf.j2
    dest: "{{ mysql_config_file }}"
    owner: root
    group: root
    mode: 0644
    force: "{{ overwrite_global_mycnf }}"
  notify: restart mysql

- name: Verify mysql include directory exists.
  ansible.builtin.file:
    path: "{{ mysql_config_include_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: mysql_config_include_files | length | bool

- name: Copy my.cnf override files into include directory.
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ mysql_config_include_dir }}/{{ item.src | basename }}"
    owner: root
    group: root
    mode: 0644
    force: "{{ item.force | default(false) }}"
  with_items: "{{ mysql_config_include_files }}"
  notify: restart mysql

- name: Create datadir if it does not exist
  ansible.builtin.file:
    path: "{{ mysql_datadir }}"
    state: directory
    owner: mysql
    group: mysql
    mode: 0755
    setype: mysqld_db_t

- name: Ensure error log directory exists
  ansible.builtin.file:
    path: "{{ mysql_log_error | dirname }}"
    state: directory
    owner: mysql
    group: "{{ mysql_log_file_group }}"
    mode: "0755"
  when:
    - mysql_log_error | default('') | length > 0
    - mysql_log_error != 'syslog'

- name: Ensure slow query log file exists and has correct permissions
  ansible.builtin.file:
    path: "{{ mysql_slow_query_log_file }}"
    state: touch
    owner: mysql
    group: "{{ mysql_log_file_group }}"
    mode: "0640"
    modification_time: preserve
    access_time: preserve
  when: mysql_slow_query_log_enabled | bool

- name: Ensure error log file exists and has correct permissions
  ansible.builtin.file:
    path: "{{ mysql_log_error }}"
    state: touch
    owner: mysql
    group: "{{ mysql_log_file_group }}"
    mode: "0640"
    modification_time: preserve
    access_time: preserve
  when:
    - mysql_log | default('') | length > 0
    - mysql_log_error | default('') | length > 0
    - mysql_log_error != 'syslog'
  tags: ['skip_ansible_galaxy']

- name: Ensure MySQL is started and enabled on boot.
  ansible.builtin.service:
    name: "{{ mysql_daemon }}"
    state: started
    enabled: "{{ mysql_enabled_on_startup }}"
  register: mysql_service_configuration
