---
- name: Ensure MySQL databases are present.
  mysql_db:
    name: "{{ item.name }}"
    collation: "{{ item.collation | default('utf8_general_ci') }}"
    encoding: "{{ item.encoding | default('utf8') }}"
    login_unix_socket: "{{ login_unix_socket | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ mysql_databases }}"
